# Generated by Django 5.1.3 on 2024-11-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artists', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('album_or_movie', models.CharField(blank=True, max_length=255, null=True)),
                ('user_rating', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
